### ISSUE TITLE
Files outside of Workspace

### ISSUE THREAD

**Issue by grafst** [rioj7/whenFile#1]
Hi
Great Extension. I would like to use it to color Files that are not from the current project.
However the extension works only inside the workpspace?
Even if I use the "byLanguageId" trigger it doesn't color files that lye outside my workspace.
Would it be possible to enhance the extension so that it works for all filepaths?

Best wishes
Stephan

**Comment by rioj7** [comment]
@grafst  try v0.5.0 uses First Workspace settings for files not in an open workspace

**Comment by grafst** [comment]
oh yes! 
thank you so much 😄
