### ISSUE TITLE
Only working if `app/...file` selected

### ISSUE THREAD

**Issue by axmairat** [rioj7/whenFile#3]
it is greatest extension! But it not working if "app/...file" not selected

![image](https://github.com/rioj7/whenFile/assets/47591259/6a05faab-1c51-4cc8-962f-045f14c4c0f9)

![image](https://github.com/rioj7/whenFile/assets/47591259/fdaee149-99b5-47ad-b352-82361acb027a)
![image](https://github.com/rioj7/whenFile/assets/47591259/1cf8b1a4-e5bd-4f7a-afaa-cc23d13b4678)

**Comment by rioj7** [comment]
@axmairat What do you expect to see?

When your **current editor** is for a file in the `app` directory it changes color.

**Comment by axmairat** [comment]
1. I want to see the colors right away. Maybe this is not exactly what I'm looking for.
Example
![image](https://github.com/rioj7/whenFile/assets/47591259/a7f9ab22-d7ce-42dc-a613-ac4480b0bf98)

2. Does this only work for the file manager? For example, will it work in plugins?
![Brush-#2](https://github.com/rioj7/whenFile/assets/47591259/590e5cdd-af8b-434f-8d81-7dfbd52c01c9)

Thanks!

**Comment by rioj7** [comment]
@axmairat 

> 1. I want to see the colors right away.

If you don't specify where you expect the color to see.

The `folder-path-color` extension uses theme names to color the folders/file with a `FileDecorationProvider` (I need to catch up on new API). The colors used are hard coded and are the `terminal` colors, He could make the extension to use any theme color name.

You want what `folder-path-color` does but with custom colors?

The colors that be used in the `FileDecorationProvider` are the theme color names. Custom colors are not supported.

----

> 2. Does this only work for the file manager? For example, will it work in plugins?

What do you expect to see?

Is the `deal_review` tab a WebView or a Custom Editor?

I have to investigate if I can get a notification for these kind of tabs activation and if I can extract some kind of identification to use.

**Comment by axmairat** [comment]
1. Perhaps I explained incorrectly. Hex color is the best. I want to always see colored folders and files so I don't get confused.

2. webview
![image](https://github.com/rioj7/whenFile/assets/47591259/5636355a-4515-42a3-be17-eaef6ddd873d)

Thanks!

**Comment by rioj7** [comment]
@axmairat  

What is `Hex color`?

AFAIK we have no control of the background color of a TreeView Item,

If the extension uses a `WebviewView` they have total control of what is shown. But you then have to implement the tree yourself or use a Web UI framework that has the tree you like, but it most likely won't operate like VSC with file URI's (git status updates,.....)

----

This extension changes the theme color customization on the fly based on the current editor:

* URI
* languageID
* dirty status
